name: Update profile artwork (Pac-Man + Snake)

on:
  schedule:
    - cron: "0 0 * * *"   #  00:00 UTC
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- SNAKE ---
      - name: Generate Snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: Nubet
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # --- PAC-MAN ---
      - name: Generate Pac-Man SVGs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # --- PUBLISH:t ---
      - name: Publish to output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update Pac-Man + Snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
